export type Category =
  | 'Chargeurs Rapides'
  | 'Câbles Premium'
  | 'Supports Téléphone'
  | 'Écouteurs Bluetooth'
  | 'Casques Audio'
  | 'Montres Connectées'
  | 'Batteries Externes'
  | 'Accessoires PC'
  | 'Gaming';

export interface Product {
  id: string;
  name: string;
  category: Category;
  price: number;
  oldPrice: number;
  discount: number;
  image: string;
  images: string[];
  rating: number;
  reviews: number;
  inStock: boolean;
  stockCount: number;
  isNew: boolean;
  isBestSeller: boolean;
  isPromo: boolean;
  brand: string;
  description: string;
  features: string[];
  delivery: string;
  warranty: string;
  badge?: string;
}

export const categories: { name: Category; icon: string; slug: string }[] = [
  { name: 'Chargeurs Rapides', icon: '⚡', slug: 'chargeurs-rapides' },
  { name: 'Câbles Premium', icon: '🔌', slug: 'cables-premium' },
  { name: 'Supports Téléphone', icon: '📱', slug: 'supports-telephone' },
  { name: 'Écouteurs Bluetooth', icon: '🎧', slug: 'ecouteurs-bluetooth' },
  { name: 'Casques Audio', icon: '🎵', slug: 'casques-audio' },
  { name: 'Montres Connectées', icon: '⌚', slug: 'montres-connectees' },
  { name: 'Batteries Externes', icon: '🔋', slug: 'batteries-externes' },
  { name: 'Accessoires PC', icon: '💻', slug: 'accessoires-pc' },
  { name: 'Gaming', icon: '🎮', slug: 'gaming' },
];

export const products: Product[] = [
  // CHARGEURS
  {
    id: 'CHG001',
    name: 'Chargeur GaN 65W Pro',
    category: 'Chargeurs Rapides',
    price: 15900,
    oldPrice: 22900,
    discount: 31,
    image: '/charger.jpg',
    images: ['/charger.jpg', '/charger.jpg'],
    rating: 4.8,
    reviews: 234,
    inStock: true,
    stockCount: 45,
    isNew: false,
    isBestSeller: true,
    isPromo: true,
    brand: 'SenTech',
    description: 'Chargeur GaN 65W ultra-compact, compatible USB-C et USB-A. Charge votre laptop, smartphone et tablette simultanément. Technologie GaN de 3ème génération pour une efficacité maximale.',
    features: ['65W USB-C PD', 'Technologie GaN III', 'Compatible MacBook Pro', 'Protection multi-niveaux', 'Compact ultra-portable'],
    delivery: '2-3 jours ouvrés',
    warranty: '2 ans',
    badge: 'BEST SELLER',
  },
  {
    id: 'CHG002',
    name: 'Chargeur 33W Turbo',
    category: 'Chargeurs Rapides',
    price: 8900,
    oldPrice: 13900,
    discount: 36,
    image: '/charger.jpg',
    images: ['/charger.jpg'],
    rating: 4.6,
    reviews: 156,
    inStock: true,
    stockCount: 78,
    isNew: true,
    isBestSeller: false,
    isPromo: true,
    brand: 'TechBoost',
    description: 'Charge rapide 33W avec protection contre la surchauffe. Compatble avec tous les smartphones récents.',
    features: ['33W Charge rapide', 'Port USB-C', 'Protection surchauffe', 'LED indicateur'],
    delivery: '2-3 jours ouvrés',
    warranty: '1 an',
    badge: 'NOUVEAU',
  },
  {
    id: 'CHG003',
    name: 'Station de Charge 4 Ports',
    category: 'Chargeurs Rapides',
    price: 21900,
    oldPrice: 31900,
    discount: 31,
    image: '/charger.jpg',
    images: ['/charger.jpg'],
    rating: 4.7,
    reviews: 89,
    inStock: true,
    stockCount: 32,
    isNew: false,
    isBestSeller: false,
    isPromo: false,
    brand: 'MultiCharge',
    description: 'Station de charge desktop 4 ports : 2x USB-C PD + 2x USB-A. Charge 4 appareils simultanément avec 100W de puissance totale.',
    features: ['100W total', '2x USB-C PD', '2x USB-A', 'Détection automatique', 'Design vertical'],
    delivery: '3-5 jours ouvrés',
    warranty: '2 ans',
  },

  // CÂBLES
  {
    id: 'CAB001',
    name: 'Câble USB-C Tressé 2m',
    category: 'Câbles Premium',
    price: 4900,
    oldPrice: 7900,
    discount: 38,
    image: '/cable.jpg',
    images: ['/cable.jpg'],
    rating: 4.9,
    reviews: 412,
    inStock: true,
    stockCount: 120,
    isNew: false,
    isBestSeller: true,
    isPromo: true,
    brand: 'SenTech',
    description: 'Câble USB-C tressé premium 2 mètres, compatible charge rapide 60W et transfert de données 480Mbps. Gaine nylon ultra-résistante.',
    features: ['2 mètres', 'Charge 60W', 'Data 480Mbps', 'Gaine nylon', '30 000+ pliages'],
    delivery: '1-2 jours ouvrés',
    warranty: '18 mois',
  },
  {
    id: 'CAB002',
    name: 'Câble Lightning MFi Certifié',
    category: 'Câbles Premium',
    price: 6900,
    oldPrice: 10900,
    discount: 37,
    image: '/cable.jpg',
    images: ['/cable.jpg'],
    rating: 4.7,
    reviews: 198,
    inStock: true,
    stockCount: 85,
    isNew: false,
    isBestSeller: false,
    isPromo: false,
    brand: 'CertiFi',
    description: 'Câble Lightning certifié MFi pour iPhone et iPad. Charge rapide et synchronisation des données garanties.',
    features: ['Certifié MFi', '1.5 mètre', 'Charge rapide', 'Data sync', 'Compatible iOS 17'],
    delivery: '2-3 jours ouvrés',
    warranty: '1 an',
  },
  {
    id: 'CAB003',
    name: 'Câble Magnétique 3-en-1',
    category: 'Câbles Premium',
    price: 8900,
    oldPrice: 13900,
    discount: 36,
    image: '/cable.jpg',
    images: ['/cable.jpg'],
    rating: 4.5,
    reviews: 267,
    inStock: true,
    stockCount: 60,
    isNew: true,
    isBestSeller: false,
    isPromo: true,
    brand: 'MagConnect',
    description: 'Câble magnétique 3-en-1 avec embouts USB-C, Micro-USB et Lightning. Connexion magnétique ultra-rapide à 360°.',
    features: ['USB-C + Micro + Lightning', 'Magnétique 360°', '1.2 mètre', '100W charge', 'Tête LED illuminée'],
    delivery: '2-3 jours ouvrés',
    warranty: '1 an',
    badge: 'NOUVEAU',
  },

  // SUPPORTS
  {
    id: 'SUP001',
    name: 'Support Téléphone Voiture',
    category: 'Supports Téléphone',
    price: 8900,
    oldPrice: 13900,
    discount: 36,
    image: '/phone_stand.jpg',
    images: ['/phone_stand.jpg'],
    rating: 4.6,
    reviews: 334,
    inStock: true,
    stockCount: 95,
    isNew: false,
    isBestSeller: true,
    isPromo: false,
    brand: 'DriveMount',
    description: 'Support téléphone voiture magnétique universel, fixation grille d\'aération. Rotation 360°, compatible tous smartphones jusqu\'à 7 pouces.',
    features: ['Magnétique universel', 'Rotation 360°', 'Grille d\'aération', 'Jusqu\'à 7"', 'Installation 1 main'],
    delivery: '2-3 jours ouvrés',
    warranty: '1 an',
  },
  {
    id: 'SUP002',
    name: 'Support Bureau Ajustable Premium',
    category: 'Supports Téléphone',
    price: 11900,
    oldPrice: 17900,
    discount: 34,
    image: '/phone_stand.jpg',
    images: ['/phone_stand.jpg'],
    rating: 4.8,
    reviews: 145,
    inStock: true,
    stockCount: 40,
    isNew: false,
    isBestSeller: false,
    isPromo: false,
    brand: 'DeskPro',
    description: 'Support bureau aluminium ajustable pour smartphone et tablette. Hauteur et angle réglables, base antidérapante.',
    features: ['Aluminium premium', 'Hauteur réglable', 'Angle 0°-100°', 'Base antidérapante', 'Compatible 4"-12.9"'],
    delivery: '3-5 jours ouvrés',
    warranty: '2 ans',
  },

  // ÉCOUTEURS
  {
    id: 'ECO001',
    name: 'Écouteurs TWS Pro X1',
    category: 'Écouteurs Bluetooth',
    price: 24900,
    oldPrice: 37900,
    discount: 34,
    image: '/earbuds.jpg',
    images: ['/earbuds.jpg'],
    rating: 4.8,
    reviews: 567,
    inStock: true,
    stockCount: 28,
    isNew: false,
    isBestSeller: true,
    isPromo: true,
    brand: 'SenTech',
    description: 'Écouteurs True Wireless avec réduction de bruit active (ANC). Autonomie 8h + 32h avec le boîtier. Son Hi-Fi 12mm driver, basses profondes.',
    features: ['ANC Active Noise Cancel', '8h + 32h autonomie', 'Bluetooth 5.3', 'IPX5 waterproof', 'Charge rapide 15min = 2h'],
    delivery: '2-3 jours ouvrés',
    warranty: '2 ans',
    badge: 'BEST SELLER',
  },
  {
    id: 'ECO002',
    name: 'Écouteurs Sport Bluetooth',
    category: 'Écouteurs Bluetooth',
    price: 16900,
    oldPrice: 24900,
    discount: 32,
    image: '/earbuds.jpg',
    images: ['/earbuds.jpg'],
    rating: 4.5,
    reviews: 289,
    inStock: true,
    stockCount: 55,
    isNew: true,
    isBestSeller: false,
    isPromo: false,
    brand: 'SportFit',
    description: 'Écouteurs sport résistants à l\'eau IPX7. Design ergonomique avec crochets d\'oreilles pour un maintien parfait lors du sport.',
    features: ['IPX7 waterproof', 'Crochets d\'oreilles', '6h autonomie', 'Mode ambient', 'Micro intégré'],
    delivery: '2-3 jours ouvrés',
    warranty: '1 an',
    badge: 'NOUVEAU',
  },
  {
    id: 'ECO003',
    name: 'Écouteurs ANC Premium Elite',
    category: 'Écouteurs Bluetooth',
    price: 35900,
    oldPrice: 52900,
    discount: 32,
    image: '/earbuds.jpg',
    images: ['/earbuds.jpg'],
    rating: 4.9,
    reviews: 178,
    inStock: true,
    stockCount: 18,
    isNew: true,
    isBestSeller: false,
    isPromo: true,
    brand: 'AudioMax',
    description: 'Écouteurs premium avec ANC hybride, son spatial 3D et codec LDAC haute résolution. L\'expérience audio ultime.',
    features: ['ANC Hybride -40dB', 'Son spatial 3D', 'LDAC Hi-Res Audio', '10h + 40h', 'LOSSLESS aptX'],
    delivery: '3-5 jours ouvrés',
    warranty: '2 ans',
    badge: 'PREMIUM',
  },

  // CASQUES
  {
    id: 'CAS001',
    name: 'Casque Audio NC Pro',
    category: 'Casques Audio',
    price: 45900,
    oldPrice: 67900,
    discount: 32,
    image: '/headphones.jpg',
    images: ['/headphones.jpg'],
    rating: 4.8,
    reviews: 203,
    inStock: true,
    stockCount: 15,
    isNew: false,
    isBestSeller: true,
    isPromo: true,
    brand: 'SenTech',
    description: 'Casque over-ear avec réduction de bruit active hybride. 30h d\'autonomie, son Hi-Fi avec driver 40mm, pliable compact.',
    features: ['ANC Hybride', '30h autonomie', 'Driver 40mm Hi-Fi', 'Pliable', 'Mode transparence'],
    delivery: '3-5 jours ouvrés',
    warranty: '2 ans',
    badge: 'TOP VENTE',
  },
  {
    id: 'CAS002',
    name: 'Casque Gaming RGB Pro',
    category: 'Casques Audio',
    price: 32900,
    oldPrice: 47900,
    discount: 31,
    image: '/headphones.jpg',
    images: ['/headphones.jpg'],
    rating: 4.6,
    reviews: 134,
    inStock: true,
    stockCount: 22,
    isNew: false,
    isBestSeller: false,
    isPromo: false,
    brand: 'GameAudio',
    description: 'Casque gaming 7.1 surround virtuel avec RGB personnalisable. Micro antibruit rétractable, compatible PC, PS5 et Xbox.',
    features: ['7.1 Surround virtuel', 'RGB 16M couleurs', 'Micro rétractable', 'Compatible multi-plateformes', 'Coussinets mémoire'],
    delivery: '3-5 jours ouvrés',
    warranty: '1 an',
  },

  // MONTRES
  {
    id: 'MON001',
    name: 'Montre Connectée Series 8',
    category: 'Montres Connectées',
    price: 59900,
    oldPrice: 89900,
    discount: 33,
    image: '/smartwatch.jpg',
    images: ['/smartwatch.jpg'],
    rating: 4.9,
    reviews: 445,
    inStock: true,
    stockCount: 20,
    isNew: false,
    isBestSeller: true,
    isPromo: true,
    brand: 'SenTech',
    description: 'Montre connectée AMOLED 1.9" avec GPS intégré, suivi santé avancé (SpO2, ECG, fréquence cardiaque). Étanche 5ATM.',
    features: ['AMOLED 1.9"', 'GPS intégré', 'ECG + SpO2', '14 jours autonomie', '5ATM étanche'],
    delivery: '3-5 jours ouvrés',
    warranty: '2 ans',
    badge: 'PREMIUM',
  },
  {
    id: 'MON002',
    name: 'Bracelet Fitness Pro X',
    category: 'Montres Connectées',
    price: 22900,
    oldPrice: 34900,
    discount: 34,
    image: '/smartwatch.jpg',
    images: ['/smartwatch.jpg'],
    rating: 4.5,
    reviews: 312,
    inStock: true,
    stockCount: 48,
    isNew: true,
    isBestSeller: false,
    isPromo: false,
    brand: 'FitBand',
    description: 'Bracelet fitness avec suivi activité, sommeil, SpO2 et 100+ modes sport. Écran AMOLED couleur, 12 jours autonomie.',
    features: ['100+ modes sport', 'Suivi sommeil', 'SpO2 + FC', '12 jours autonomie', 'Notifications smartphone'],
    delivery: '2-3 jours ouvrés',
    warranty: '1 an',
    badge: 'NOUVEAU',
  },

  // BATTERIES
  {
    id: 'BAT001',
    name: 'Power Bank 20000mAh 65W',
    category: 'Batteries Externes',
    price: 19900,
    oldPrice: 29900,
    discount: 33,
    image: '/powerbank.jpg',
    images: ['/powerbank.jpg'],
    rating: 4.8,
    reviews: 389,
    inStock: true,
    stockCount: 35,
    isNew: false,
    isBestSeller: true,
    isPromo: true,
    brand: 'SenTech',
    description: 'Batterie externe 20000mAh avec charge rapide 65W PD. Charge laptop, tablette et smartphone simultanément. Affichage LED de charge.',
    features: ['20000mAh', '65W PD USB-C', '3 ports sortie', 'Affichage LED', 'Charge sans fil 15W'],
    delivery: '2-3 jours ouvrés',
    warranty: '2 ans',
    badge: 'BEST SELLER',
  },
  {
    id: 'BAT002',
    name: 'Power Bank Sans Fil 10000mAh',
    category: 'Batteries Externes',
    price: 24900,
    oldPrice: 36900,
    discount: 33,
    image: '/powerbank.jpg',
    images: ['/powerbank.jpg'],
    rating: 4.7,
    reviews: 198,
    inStock: true,
    stockCount: 26,
    isNew: true,
    isBestSeller: false,
    isPromo: false,
    brand: 'WirelessPower',
    description: 'Power Bank 10000mAh avec charge sans fil Qi 15W intégrée. Slim design ultra-fin, compatible MagSafe.',
    features: ['10000mAh', 'Qi 15W sans fil', 'Compatible MagSafe', '22.5W filaire', 'Ultra-slim 13mm'],
    delivery: '3-5 jours ouvrés',
    warranty: '1 an',
    badge: 'NOUVEAU',
  },
  {
    id: 'BAT003',
    name: 'Batterie MagSafe 5000mAh',
    category: 'Batteries Externes',
    price: 27900,
    oldPrice: 39900,
    discount: 30,
    image: '/powerbank.jpg',
    images: ['/powerbank.jpg'],
    rating: 4.6,
    reviews: 145,
    inStock: true,
    stockCount: 30,
    isNew: true,
    isBestSeller: false,
    isPromo: true,
    brand: 'MagPower',
    description: 'Batterie MagSafe 5000mAh qui se fixe magnétiquement à votre iPhone. Charge à 15W, compatible iPhone 12/13/14/15.',
    features: ['MagSafe magnétique', '15W charge rapide', '5000mAh', 'iPhone 12-15', 'Ultra-compact'],
    delivery: '2-3 jours ouvrés',
    warranty: '1 an',
    badge: 'NOUVEAU',
  },

  // ACCESSOIRES PC
  {
    id: 'PC001',
    name: 'Hub USB-C 9-en-1',
    category: 'Accessoires PC',
    price: 21900,
    oldPrice: 32900,
    discount: 33,
    image: '/laptop_stand.jpg',
    images: ['/laptop_stand.jpg'],
    rating: 4.7,
    reviews: 234,
    inStock: true,
    stockCount: 42,
    isNew: false,
    isBestSeller: true,
    isPromo: false,
    brand: 'HubPro',
    description: 'Hub USB-C 9-en-1 : HDMI 4K, 3x USB-A, USB-C PD 100W, SD/TF card, RJ45 Ethernet. Compatible MacBook et PC Windows.',
    features: ['HDMI 4K@60Hz', '3x USB-A 3.0', 'USB-C PD 100W', 'RJ45 Ethernet', 'SD + TF card'],
    delivery: '2-3 jours ouvrés',
    warranty: '2 ans',
  },
  {
    id: 'PC002',
    name: 'Support Laptop Premium',
    category: 'Accessoires PC',
    price: 17900,
    oldPrice: 26900,
    discount: 33,
    image: '/laptop_stand.jpg',
    images: ['/laptop_stand.jpg'],
    rating: 4.8,
    reviews: 167,
    inStock: true,
    stockCount: 38,
    isNew: false,
    isBestSeller: false,
    isPromo: false,
    brand: 'DeskPro',
    description: 'Support laptop aluminium premium, hauteur réglable en 6 niveaux. Compatible 11" à 17". Améliore la posture et le refroidissement.',
    features: ['Aluminium premium', '6 hauteurs réglables', '11" à 17"', 'Pliable portable', 'Antidérapant'],
    delivery: '3-5 jours ouvrés',
    warranty: '2 ans',
  },
  {
    id: 'PC003',
    name: 'Webcam HD 1080p Pro',
    category: 'Accessoires PC',
    price: 17900,
    oldPrice: 25900,
    discount: 31,
    image: '/laptop_stand.jpg',
    images: ['/laptop_stand.jpg'],
    rating: 4.6,
    reviews: 198,
    inStock: true,
    stockCount: 25,
    isNew: true,
    isBestSeller: false,
    isPromo: false,
    brand: 'StreamPro',
    description: 'Webcam 1080p 60fps avec micro stéréo intégré et correction automatique de la lumière. Idéale télétravail et streaming.',
    features: ['1080p 60fps', 'Correction lumière AI', 'Micro stéréo', 'Champ 90°', 'Plug & play'],
    delivery: '2-3 jours ouvrés',
    warranty: '1 an',
    badge: 'NOUVEAU',
  },
  {
    id: 'PC004',
    name: 'Adaptateur USB-C vers HDMI 4K',
    category: 'Accessoires PC',
    price: 8900,
    oldPrice: 13900,
    discount: 36,
    image: '/cable.jpg',
    images: ['/cable.jpg'],
    rating: 4.5,
    reviews: 312,
    inStock: true,
    stockCount: 80,
    isNew: false,
    isBestSeller: false,
    isPromo: false,
    brand: 'ConnectPro',
    description: 'Adaptateur USB-C vers HDMI 4K@60Hz. Compatible Thunderbolt 3/4, MacBook, iPad Pro, Galaxy S/Tab.',
    features: ['4K@60Hz', 'USB-C Thunderbolt', 'MacBook compatible', 'Galaxy compatible', 'Plug & play'],
    delivery: '1-2 jours ouvrés',
    warranty: '1 an',
  },

  // GAMING
  {
    id: 'GAM001',
    name: 'Souris Gaming RGB Pro',
    category: 'Gaming',
    price: 14900,
    oldPrice: 22900,
    discount: 35,
    image: '/gaming_mouse.jpg',
    images: ['/gaming_mouse.jpg'],
    rating: 4.7,
    reviews: 456,
    inStock: true,
    stockCount: 52,
    isNew: false,
    isBestSeller: true,
    isPromo: true,
    brand: 'GamePro',
    description: 'Souris gaming ergonomique avec capteur optique 25600 DPI, RGB 16M couleurs, 6 boutons programmables. Clics optiques ultra-précis.',
    features: ['25600 DPI', 'RGB 16M couleurs', '6 boutons prog.', 'Clics optiques', '70h sans fil'],
    delivery: '2-3 jours ouvrés',
    warranty: '2 ans',
    badge: 'BEST SELLER',
  },
  {
    id: 'GAM002',
    name: 'Manette Gaming Bluetooth Pro',
    category: 'Gaming',
    price: 28900,
    oldPrice: 42900,
    discount: 33,
    image: '/gaming_mouse.jpg',
    images: ['/gaming_mouse.jpg'],
    rating: 4.7,
    reviews: 234,
    inStock: true,
    stockCount: 18,
    isNew: false,
    isBestSeller: false,
    isPromo: true,
    brand: 'GamePro',
    description: 'Manette gaming Bluetooth compatible PC, Android, iOS, PS4/PS5. Joysticks Hall Effect, gâchettes adaptatives, vibration haptique.',
    features: ['Hall Effect joysticks', 'Gâchettes adaptatives', 'Bluetooth 5.2', 'PC + Android + iOS', '20h autonomie'],
    delivery: '3-5 jours ouvrés',
    warranty: '1 an',
  },
  {
    id: 'GAM003',
    name: 'Clavier Mécanique Gaming',
    category: 'Gaming',
    price: 39900,
    oldPrice: 57900,
    discount: 31,
    image: '/gaming_mouse.jpg',
    images: ['/gaming_mouse.jpg'],
    rating: 4.8,
    reviews: 178,
    inStock: true,
    stockCount: 12,
    isNew: true,
    isBestSeller: false,
    isPromo: false,
    brand: 'MechaKey',
    description: 'Clavier mécanique TKL avec switches Red (linéaires), rétroéclairage RGB par touche, mode sans fil 2.4GHz.',
    features: ['Switches Red linéaires', 'RGB par touche', 'Sans fil 2.4GHz', 'TKL compact', '6000mAh batterie'],
    delivery: '3-5 jours ouvrés',
    warranty: '2 ans',
    badge: 'NOUVEAU',
  },
  {
    id: 'GAM004',
    name: 'Casque VR Standalone',
    category: 'Gaming',
    price: 89900,
    oldPrice: 129900,
    discount: 31,
    image: '/headphones.jpg',
    images: ['/headphones.jpg'],
    rating: 4.6,
    reviews: 89,
    inStock: true,
    stockCount: 8,
    isNew: true,
    isBestSeller: false,
    isPromo: true,
    brand: 'VirtualX',
    description: 'Casque VR standalone 4K per eye, sans PC ni câble. Bibliothèque 500+ jeux, tracking 6DoF, contrôleurs inclus.',
    features: ['4K per eye', 'Sans PC requis', '500+ jeux', '6DoF tracking', '3h autonomie'],
    delivery: '5-7 jours ouvrés',
    warranty: '2 ans',
    badge: 'PREMIUM',
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category);
}

export function getBestSellers(): Product[] {
  return products.filter(p => p.isBestSeller);
}

export function getNewProducts(): Product[] {
  return products.filter(p => p.isNew);
}

export function getPromoProducts(): Product[] {
  return products.filter(p => p.isPromo);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('fr-FR').format(price) + ' FCFA';
}
